ox-it/talks.ox

static/js/event-form.js
static/js/form-controls.js

A copy of #171 without the last 2 commits (an attempt to use slug as value within the forms).
Now fixes #169 and the functional issue with group picking described in #173

No duplicate suggestions (still using ids)

---

talks/events/forms.py
talks/events/migrations/0019_auto_20150107_1008.py
talks/events/models.py
talks/events/tests.py
talks/events/views.py
talks/templates/events/_event_group_form_fields.html
talks/templates/events/event-group.html
talks/templates/events/event_form.html
talks/templates/events/event_group_form.html
talks/templates/events/event_group_modal_form.html
talks/templates/events/person_form.html
talks/templates/events/person_quick_add.html

Create person in event-series form

---

requirements.txt
talks/settings.py

Installed and configured django-cors-headers

---

talks/api/serializers.py
talks/api/views.py
talks/events/models.py
talks/urls.py

Additions to the talks api as outlined in #68

Talks api additions

---

talks/old_talks/models.py
talks/old_talks/tests.py

#228 Append more fields to abstract when pushing to old talks
#227 More params pushed to old series

Updates to push to old talks

---

static/js/event-form.js
static/js/form-controls.js
tests/edit_talk.robot
tests/events.py
tests/fixtures.py
tests/keywords.robot

#217
When picking a series, the series' organisers are added to the event's organisers, if not already there.

Organisers propagate from series

---

static/js/event-form.js

Fix for BST form issue

---

talks/old_talks/models.py
talks/old_talks/tests.py

Push old talks extras

---

talks/contributors/forms.py
talks/contributors/tests.py
talks/contributors/views.py
talks/events/migrations/0003_eventgroup_editor_set.py
talks/events/models.py
talks/events/templatetags/users.py
talks/templates/contributors/_event_group_form_fields.html
talks/templates/contributors/contributors_events.html
talks/templates/contributors/contributors_groups.html
talks/templates/events/event-group.html
talks/templates/events/event.html
tests/add_talk.robot

Series permissions

---

fabfile.py

This change coincides with the changes made in the talks-prod branch of the puppet repo.

Talks prod

---

solr/schema.xml
talks/events/search_indexes.py
talks/events_search/conf.py
talks/templates/search/search.html

Search on series title, facet on series.

---

static/js/event-form.js
talks/contributors/views.py
talks/old_talks/tasks.py

Add timeouts for when pushing to old talks. 

---

requirements.txt
requirements_dev.txt
talks/core/utils.py
talks/settings.py
talks/settings_dev.py

Reads the 'url' key in (talks/solr_location.yaml). 
Also, use Simple db querying in local dev mode.

Read solr_location from local file on server 

---

talks/contributors/views.py
talks/events/migrations/0008_auto_20150318_1624.py
talks/events/models.py
talks/old_talks/models.py
talks/templates/contributors/contributors_persons.html
talks/templates/events/person.html

Make affiliation optional. Some changes to templates to behave better for missing affiliation. Filter on dashboard to see only people with no affiliation.
#283

Affiliation optional

---

static/css/custom.css
static/js/form-controls.js
talks/api/services.py
talks/contributors/forms.py
talks/core/utils.py
talks/events/forms.py
talks/events/views.py
talks/templates/events/browse.html

Browse by venue

---

talks/api/services.py
talks/api/urls.py
talks/api/views.py
talks/events/datasources.py
talks/events/forms.py
talks/events/views.py
talks/templates/base.html
talks/templates/events/browse.html
talks/templates/front.html

Added browse by series and refactored events_search to take a parameters dict instead of the whole request object.

Browse by series

---

talks/events/models.py
talks/templates/events/department.html
talks/templates/events/department_ics_link.html
talks/templates/events/department_plain_text_link.html
talks/templates/events/event-group.html
talks/templates/events/event_group_ics_link.html
talks/templates/events/event_group_plain_text_link.html
talks/templates/events/event_ics_link.html
talks/templates/events/event_plain_text_link.html
talks/templates/events/person.html
talks/templates/events/person_plain_text_link.html
talks/templates/events/topic.html
talks/templates/events/topic_plain_text_link.html
talks/templates/users/add_to_collections_widget.html
talks/templates/users/collection_ics_link.html
talks/templates/users/collection_plain_text_link.html
talks/templates/users/collection_view.html

1. links and icons for collections
2. put additional information underneath the Show Upcoming | Show All
links for Series and Collection
3. Edit button in blue bar for collection as for series
4. Only show series description if there is one
5. Replace Untitled Talk with Talk TBC

Simplify text and icons

---

talks/users/views.py

Sort collections alphabetically in public lists

Sort talks in public lists alphabetically

---

talks/events/views.py
talks/templates/events/_event_list.html
talks/templates/events/_event_list.txt.html
talks/templates/events/browse.html
talks/templates/events/department.html
talks/templates/events/department.txt.html
talks/templates/events/event-group.html
talks/templates/events/event-group.txt.html
talks/templates/events/event.txt.html
talks/templates/events/event_teaser.html
talks/templates/events/event_teaser.txt.html
talks/templates/events/person.html
talks/templates/events/person.txt.html
talks/templates/events/topic.html
talks/templates/events/topic.txt.html
talks/templates/users/collection_view.html
talks/templates/users/collection_view.txt.html
talks/users/views.py

use event-teaser template to display the talks consistently,
group the events by date,
show editor in talks, series
show "in preparation status" status in talks lists

Display talks consistently

---

static/css/custom.css
talks/events/views.py
talks/templates/events/browse.html

browse page: construct queries and make links for:
all, today ,tomorrow , this week, next week, next 30 days

Date tabs in browse - 3067

---

talks/old_talks/admin.py
talks/users/admin.py
talks/users/models.py

Remove old talks from admin interface

Allow transferring ownership of a public list via the admin interface.

---

talks/contributors/forms.py
talks/contributors/views.py
talks/events/models.py

List speakers in the order they were entered.

Speaker order

---

talks/events/views.py
talks/templates/events/topic.html

Added "show upcoming talks only" button and view code

---

static/css/custom.css
talks/events/views.py
talks/templates/events/_event_list.html

3291- take bottom border off last table of results on each page

Deal with paging grouping

---

talks/events/views.py
talks/events_search/views.py
talks/templates/events/event_teaser.html
talks/templates/search/search.html
talks/templates/search/search_past.html

3505 - Group search results by Oxford date

search: format date to oxford-date

---

talks/api/serializers.py
talks/api/urls.py
talks/api/views.py
talks/events/models.py
talks/templates/events/person.html
talks/templates/events/person_ics_link.html

Add speaker routes to api for normal api and for ics
Add ical link to speaker page.

Speaker api ical 3481

---

talks/api/services.py
talks/api/views.py
talks/core/utils.py

Option to have query param of to=plus[int], e.g.
..../search?from=today&to=plus7

Add time delta for api date ranges - 3747

---

requirements.txt
requirements_dev.txt
talks/events/models.py
talks/events/views.py

Upgrade django and affected dependencies.
A few small code changes to fix breakages.
Deprecations for 1.9 not addressed.

Django 1.8

---

requirements.txt
talks/api/serializers.py
talks/api/tests.py
talks/core/renderers.py
talks/core/tests.py
talks/events/models.py

To address issue #494.
N.b. moved logic to generate combined name and bio into Person model from talks/core/renderers.py.

Added more informative description for ics exports

---

fabfile.py
requirements.txt
static/js/event-form.js
static/js/modal-form.js
talks/api/serializers.py
talks/api/urls.py
talks/audit_trail/urls.py
talks/contributors/forms.py
talks/contributors/urls.py
talks/core/renderers.py
talks/core/utils.py
talks/events/search_indexes.py
talks/events/urls.py
talks/events/views.py
talks/settings.py
talks/templates/auth/logged_out.html
talks/urls.py
talks/users/models.py
talks/users/urls.py
talks/users/views.py

The ox-it django-shibboleth module isn't compatible with the previous version of django used by talks (1.7). This branch upgrades django to 1.11, replaces webauth integration with shibboleth integration, and fixes any bugs that arose out of these upgrades.

Shibboleth (and Django 1.11)

---

fabfile.py
requirements.txt

The API was broken, seemingly by the upgrade to Django 1.11. This branch (along with updating the server to ubuntu 18.04, and Python 2.7.17) fixed it on dev.

Api bugfix jul20
